# Generated by Django 4.2.4 on 2023-08-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summarization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedpdf",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
